import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

test("cli login route exposes the zero-movement auth control room", () => {
  const page = readFileSync("packages/web/src/app/cli-login/page.tsx", "utf8");
  const entry = readFileSync("packages/web/src/app/cli-login/cli-login-entry.tsx", "utf8");
  const entryStyles = readFileSync("packages/web/src/app/cli-login/cli-login-entry.css", "utf8");
  const routeLayout = readFileSync("packages/web/src/app/cli-login/layout.tsx", "utf8");
  const layout = readFileSync("packages/web/src/app/layout.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/globals.css", "utf8");

  assert.match(layout, /href="\/how-to"/);   // reachable from the header
  assert.match(page, /buildDeviceAuthControlRoom/);
  assert.match(page, /buildDeviceApprovalChamber/);
  assert.match(page, /DeviceAuthControlRoomPanel/);
  assert.match(page, /DeviceApprovalChamberPanel/);
  assert.match(page, /device-auth-control-room/);
  assert.match(page, /device-approval-chamber/);
  assert.match(page, /device-approval-chamber__terminal/);
  assert.match(page, /device-approval-chamber__stages/);
  assert.match(page, /device-approval-chamber__counters/);
  assert.match(page, /device-auth-control-terminal/);
  assert.match(page, /device-auth-control-counters/);
  assert.match(page, /device-auth-control-signals/);
  assert.match(page, /device-auth-control-invariants/);
  assert.match(page, /VTK:\/\/CLI-AUTH-CONTROL\/\/IDENTITY-ONLY\/\/ZERO-USAGE-MOVEMENT/);
  assert.match(page, /VTK:\/\/APPROVAL-CHAMBER\/\/CLI-AUTH\/\/ZERO-USAGE-MOVE/);
  assert.match(page, /chamber@cli-auth/);
  assert.match(page, /chamber\.counters\.hiddenUploads/);
  assert.match(page, /chamber\.stages\.map/);
  assert.match(page, /stage\.transcript\.map/);
  assert.match(page, /control@cli-auth/);
  assert.match(page, /providerCalls/);
  assert.match(page, /promptReads/);
  assert.match(page, /outputReads/);
  assert.match(page, /usageUploads/);
  assert.match(page, /ledgerWrites/);
  assert.match(page, /signal\.impact === "not_usage"/);
  assert.match(page, /signal\.source/);
  assert.match(page, /signal\.target/);
  assert.match(page, /Vibers Unite/);
  assert.match(page, /c0vibe\.app/);
  assert.match(page, /import \{ CliLoginEntry \} from "\.\/cli-login-entry"/);
  assert.match(page, /import "\.\/cli-login-entry\.css"/);
  assert.match(page, /if \(!ready \|\| !code\) return <CliLoginEntry checking=\{!ready\} \/>/);
  assert.ok(page.indexOf("if (!ready || !code)") < page.lastIndexOf("buildDeviceApprovalChamber(state, code)"));
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/);

  assert.match(entry, /Connect your terminal\./);
  assert.match(entry, /npx vibetracker login/);
  assert.match(entry, /href="\/account\?returnTo=%2Fcli-login"/);
  assert.match(entry, /Sign in with GitHub/);
  assert.match(entry, /GitHub proof is not usage proof\./);
  assert.match(entry, /prompt reads<\/dt><dd>0/);
  assert.match(entry, /provider calls<\/dt><dd>0/);
  assert.match(entry, /hidden uploads<\/dt><dd>0/);
  assert.match(entry, /ledger writes<\/dt><dd>0/);
  assert.match(entry, /aria-live="polite"/);
  assert.match(entry, /navigator\.clipboard\.writeText\(LOGIN_COMMAND\)/);
  assert.doesNotMatch(entry, /dangerouslySetInnerHTML/);
  assert.match(routeLayout, /title: "Connect the CLI · VibeUsage"/);

  assert.match(entryStyles, /\.cli-entry__header/);
  assert.match(entryStyles, /grid-template-columns: minmax\(0, 1\.08fr\) minmax\(360px, \.92fr\)/);
  assert.match(entryStyles, /@media \(max-width: 620px\)/);
  assert.match(entryStyles, /@media \(min-width: 2200px\)/);
  assert.match(entryStyles, /width: min\(2640px, 95vw\)/);
  assert.match(entryStyles, /margin-left: 50%/);
  assert.match(entryStyles, /transform: translateX\(-50%\)/);
  assert.match(entryStyles, /@media \(prefers-reduced-motion: reduce\)/);

  assert.match(styles, /\.device-auth-control-room/);
  assert.match(styles, /\.device-approval-chamber/);
  assert.match(styles, /\.device-approval-chamber__terminal/);
  assert.match(styles, /\.device-approval-chamber__stages/);
  assert.match(styles, /\.device-approval-chamber-stage__screen/);
  assert.match(styles, /\.device-approval-chamber__stages article\[data-impact="not_usage"\]/);
  assert.match(styles, /\.device-approval-chamber__stages em::before/);
  assert.match(styles, /\.device-auth-control-room__head/);
  assert.match(styles, /\.device-auth-control-terminal/);
  assert.match(styles, /\.device-auth-control-counters/);
  assert.match(styles, /\.device-auth-control-signals/);
  assert.match(styles, /\.device-auth-control-signals article\[data-impact="not_usage"\]/);
  assert.match(styles, /\.device-auth-control-signal__meter i/);
  assert.match(styles, /\.device-auth-control-invariants/);
  assert.match(styles, /prefers-reduced-motion: reduce/);
  assert.match(styles, /device-approval-chamber-stage__screen pre:first-child/);
  assert.match(styles, /@media \(max-width: 1040px\)/);
  assert.match(styles, /@media \(max-width: 760px\)/);
});
