import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

test("cli login route exposes the zero-movement auth control room", () => {
  const page = readFileSync("packages/web/src/app/cli-login/page.tsx", "utf8");
  const layout = readFileSync("packages/web/src/app/layout.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/globals.css", "utf8");

  assert.match(layout, /href="\/how-to"/);   // reachable from the header
  assert.match(page, /buildDeviceAuthControlRoom/);
  assert.match(page, /buildDeviceApprovalChamber/);
  assert.match(page, /DeviceAuthControlRoomPanel/);
  assert.match(page, /DeviceApprovalChamberPanel/);
  assert.match(page, /device-auth-control-room/);
  assert.match(page, /device-approval-chamber/);
  assert.match(page, /device-approval-chamber__terminal/);
  assert.match(page, /device-approval-chamber__stages/);
  assert.match(page, /device-approval-chamber__counters/);
  assert.match(page, /device-auth-control-terminal/);
  assert.match(page, /device-auth-control-counters/);
  assert.match(page, /device-auth-control-signals/);
  assert.match(page, /device-auth-control-invariants/);
  assert.match(page, /VTK:\/\/CLI-AUTH-CONTROL\/\/IDENTITY-ONLY\/\/ZERO-USAGE-MOVEMENT/);
  assert.match(page, /VTK:\/\/APPROVAL-CHAMBER\/\/CLI-AUTH\/\/ZERO-USAGE-MOVE/);
  assert.match(page, /chamber@cli-auth/);
  assert.match(page, /chamber\.counters\.hiddenUploads/);
  assert.match(page, /chamber\.stages\.map/);
  assert.match(page, /stage\.transcript\.map/);
  assert.match(page, /control@cli-auth/);
  assert.match(page, /providerCalls/);
  assert.match(page, /promptReads/);
  assert.match(page, /outputReads/);
  assert.match(page, /usageUploads/);
  assert.match(page, /ledgerWrites/);
  assert.match(page, /signal\.impact === "not_usage"/);
  assert.match(page, /signal\.source/);
  assert.match(page, /signal\.target/);
  assert.match(page, /Vibers Unite/);
  assert.match(page, /c0vibe\.app/);
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/);

  assert.match(styles, /\.device-auth-control-room/);
  assert.match(styles, /\.device-approval-chamber/);
  assert.match(styles, /\.device-approval-chamber__terminal/);
  assert.match(styles, /\.device-approval-chamber__stages/);
  assert.match(styles, /\.device-approval-chamber-stage__screen/);
  assert.match(styles, /\.device-approval-chamber__stages article\[data-impact="not_usage"\]/);
  assert.match(styles, /\.device-approval-chamber__stages em::before/);
  assert.match(styles, /\.device-auth-control-room__head/);
  assert.match(styles, /\.device-auth-control-terminal/);
  assert.match(styles, /\.device-auth-control-counters/);
  assert.match(styles, /\.device-auth-control-signals/);
  assert.match(styles, /\.device-auth-control-signals article\[data-impact="not_usage"\]/);
  assert.match(styles, /\.device-auth-control-signal__meter i/);
  assert.match(styles, /\.device-auth-control-invariants/);
  assert.match(styles, /prefers-reduced-motion: reduce/);
  assert.match(styles, /device-approval-chamber-stage__screen pre:first-child/);
  assert.match(styles, /@media \(max-width: 1040px\)/);
  assert.match(styles, /@media \(max-width: 760px\)/);
});
