import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

test("home route opens with an all-viber terminal spectrum", () => {
  const page = readFileSync("packages/web/src/app/page.tsx", "utf8");
  const layout = readFileSync("packages/web/src/app/layout.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/globals.css", "utf8");

  assert.match(layout, /href="\/life">AI Life/);
  assert.match(layout, /href="\/wizard"><span>05<\/span>Wizard/);
  assert.match(layout, /href="\/motion"><span>06<\/span>Motion lab/);

  assert.match(page, /HomeViberSpectrumPreludePanel/);
  assert.match(page, /LeaderboardHeatgridPanel/);
  assert.match(page, /VTK:\/\/BOARD-HEATGRID\/\/OFFICIAL-GH-COLORS\/\/VISUAL-ONLY/);
  assert.match(page, /Official GitHub contribution color levels/);
  assert.match(page, /homeViberSpectrum/);
  assert.match(page, /home-viber-spectrum/);
  assert.match(page, /VTK:\/\/HOME-VIBER-SPECTRUM\/\/AI-LIFE\/\/VIBERS-UNITE/);
  assert.match(page, /\$ vibetrack scan --all-vibers --dry-run/);
  assert.match(page, /Not only coders: creators, researchers, local labs, global providers, trust signals, and C0VIBE publishing/);
  assert.match(page, /Higgsfield, Runway, Pika, Suno, ElevenLabs, ComfyUI/);
  assert.match(page, /Codex, GitHub, packages, Replicate CLI, and contribution cadence become trust evidence, not spend/);
  assert.match(page, /Ollama, LM Studio, ComfyUI, InvokeAI, vLLM/);
  assert.match(page, /Qwen, Kimi, DeepSeek, Mistral, Le Chat, Stability/);
  assert.match(page, /Poe, Perplexity, Hugging Face, Notion, Obsidian/);
  assert.match(page, /Profile, Vibe Score, heatgrid, and public board feed only from reviewed aggregate datastreams/);
  assert.match(page, /providerCalls=0 hiddenUpload=0 promptReads=0 outputReads=0/);
  assert.match(page, /trust != usage/);
  assert.match(page, /review before publish/);
  assert.match(page, /Vibers Unite \/\/ C0vibe\.app/);
  assert.match(page, /HeroScanBridgePanel/);
  assert.match(page, /HomeBootPanoramaPanel/);
  assert.match(page, /buildHomeDatastreamReactor/);
  assert.match(page, /HomeDatastreamReactorPanel/);
  assert.match(page, /home-datastream-reactor/);
  assert.match(page, /VTK:\/\/DATASTREAM-REACTOR\/\/SCORE-PROFILE-HEATGRID\/\/C0VIBE/);
  assert.match(page, /reactor@vibetracker/);
  assert.match(page, /REVIEWED STREAM/);
  assert.match(page, /reactor\.nodes\.map/);
  assert.match(page, /reactor\.seals\.map/);
  assert.match(page, /reactor\.totals\.heatgridFeeds/);
  assert.match(page, /reactor\.totals\.notUsageNodes/);
  assert.match(page, /node\.feeds\.heatgrid/);
  assert.ok(page.indexOf("<HomeBootPanoramaPanel") < page.indexOf("<HomeDatastreamReactorPanel reactor={datastreamReactor} />"));
  assert.ok(page.indexOf("<HomeDatastreamReactorPanel reactor={datastreamReactor} />") < page.indexOf("<HomeControlTowerPanel tower={controlTower} />"));
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/);

  assert.match(styles, /\.home-viber-spectrum/);
  assert.match(styles, /\.home-viber-spectrum__terminal/);
  assert.match(styles, /\.home-viber-spectrum__counters/);
  assert.match(styles, /\.home-viber-spectrum__lanes/);
  assert.match(styles, /\.home-viber-spectrum-lane/);
  assert.match(styles, /\.leaderboard-heatgrid__grid/);
  assert.match(styles, /\.leaderboard-heatgrid-cell\[data-level="4"\]/);
  assert.match(styles, /BOARD HEATGRID \/\/ OFFICIAL GH COLORS \/\/ VISUAL ONLY/);
  assert.match(styles, /\.home-viber-spectrum-lane--trust/);
  assert.match(styles, /\.home-viber-spectrum-lane--local/);
  assert.match(styles, /\.home-viber-spectrum-lane--privacy/);
  assert.match(styles, /\.home-viber-spectrum-lane--publish/);
  assert.match(styles, /\.home-viber-spectrum-lane__screen pre:first-child/);
  assert.match(styles, /\.home-datastream-reactor/);
  assert.match(styles, /SCORE \/ PROFILE \/ HEATGRID \/ C0VIBE/);
  assert.match(styles, /\.home-datastream-reactor__terminal/);
  assert.match(styles, /\.home-datastream-reactor__orbit/);
  assert.match(styles, /\.home-datastream-reactor__nodes/);
  assert.match(styles, /\.home-datastream-node/);
  assert.match(styles, /\.home-datastream-node--trust/);
  assert.match(styles, /\.home-datastream-node__screen pre:first-child/);
  assert.match(styles, /\.home-datastream-node__feeds span\[data-on="true"\]/);
  assert.match(styles, /\.home-datastream-node footer em::before/);
  assert.match(styles, /@media \(max-width: 1040px\)[\s\S]*\.home-viber-spectrum__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /@media \(max-width: 1040px\)[\s\S]*\.home-datastream-reactor__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /@media \(max-width: 1040px\)[\s\S]*\.home-datastream-reactor__nodes \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 1040px\)[\s\S]*\.home-viber-spectrum__lanes \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.home-viber-spectrum__lanes \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.home-datastream-reactor__nodes \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 460px\)[\s\S]*\.home-viber-spectrum__lanes \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /@media \(max-width: 460px\)[\s\S]*\.home-datastream-reactor__nodes \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.home-viber-spectrum-lane__screen pre \{ opacity: 0; transform: none; \}/);
  assert.match(styles, /\.home-datastream-node__screen pre \{ opacity: 0; transform: none; \}/);
});
