import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

test("insights lab is exposed as a first-class estimate-only analytics route", () => {
  const page = readFileSync("packages/web/src/app/insights/page.tsx", "utf8");
  const layout = readFileSync("packages/web/src/app/layout.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/globals.css", "utf8");
  const intelligence = readFileSync("packages/web/src/lib/profile-intelligence.ts", "utf8");

  assert.match(layout, /href="\/insights">Insights/);
  assert.match(page, /buildProfileIntelligenceDeck/);
  assert.match(page, /buildProfileDecisionBoard/);
  assert.match(page, /buildInsightsBudgetPulse/);
  assert.match(page, /buildInsightsPrivateScopeRadar/);
  assert.match(page, /buildInsightsRoiSwitchboard/);
  assert.match(page, /insightsLabProfile/);
  assert.match(page, /insights-route-intro/);
  assert.match(page, /InsightsBudgetPulsePanel/);
  assert.match(page, /InsightsRoiSwitchboardPanel/);
  assert.match(page, /InsightsCostRadarPanel/);
  assert.match(page, /InsightsDecisionRadarPanel/);
  assert.match(page, /InsightsPrivateScopeRadarPanel/);
  assert.match(page, /InsightsDecisionBoardPanel/);
  assert.match(page, /insights-decision-radar/);
  assert.match(page, /insights-decision-radar-node/);
  assert.match(page, /insights-private-scope/);
  assert.match(page, /insights-private-scope-lane/);
  assert.match(page, /insights-budget-pulse/);
  assert.match(page, /insights-budget-lane/);
  assert.match(page, /insights-roi-switchboard/);
  assert.match(page, /insights-roi-lever/);
  assert.match(page, /insights-cost-radar/);
  assert.match(page, /insights-radar-lane/);
  assert.match(page, /insights-decision-board/);
  assert.match(page, /insights-decision-action/);
  assert.match(page, /insights-lab profile-intelligence/);
  assert.match(page, /VTK:\/\/INSIGHTS-LAB\/\/BUDGET-PULSE\/\/NO-WRITES/);
  assert.match(page, /VTK:\/\/INSIGHTS-ROI-SWITCHBOARD\/\/NO-WRITES\/\/NOT-BILLING/);
  assert.match(page, /VTK:\/\/INSIGHTS-LAB\/\/ESTIMATE-ONLY\/\/NO-TOTALS-MUTATION/);
  assert.match(page, /VTK:\/\/INSIGHTS-DECISION-RADAR\/\/ESTIMATE-ONLY\/\/NO-WRITES/);
  assert.match(page, /VTK:\/\/INSIGHTS-PRIVATE-SCOPE\/\/ACCOUNT-PROFILE-TEAM\/\/LOCAL-ONLY/);
  assert.match(page, /VTK:\/\/INSIGHTS-LAB\/\/COST-RADAR\/\/ESTIMATE-ONLY/);
  assert.match(page, /VTK:\/\/COST-RADAR\/\/ESTIMATE-ONLY\/\/NO-TOTALS-MUTATION/);
  assert.match(page, /VTK:\/\/INSIGHTS-DECISIONS\/\/ESTIMATE-ONLY\/\/NO-WRITES/);
  assert.match(page, /ESTIMATE ONLY/);
  assert.match(page, /budget@insights/);
  assert.match(page, /roi@insights/);
  assert.match(page, /radar@insights/);
  assert.match(page, /vibetracker insights --radar/);
  assert.match(page, /scope@insights/);
  assert.match(page, /LOCAL ONLY/);
  assert.match(page, /privateScopeRadar/);
  assert.match(page, /radar\.lanes\.map/);
  assert.match(page, /lane\.proof\.map/);
  assert.match(page, /private rails/);
  assert.match(page, /rank mutations/);
  assert.match(page, /hidden uploads/);
  assert.match(page, /Decision radar/);
  assert.match(page, /Burn forecast/);
  assert.match(page, /Provider spread/);
  assert.match(page, /Local shadow/);
  assert.match(page, /Review queue/);
  assert.match(page, /0 MUTATIONS/);
  assert.match(page, /NO WRITES/);
  assert.match(page, /NO TOTALS MUTATION/);
  assert.match(page, /NO WRITE/);
  assert.match(page, /NOT SPEND/);
  assert.match(page, /pulse\.lanes\.map/);
  assert.match(page, /lane\.transcript\.map/);
  assert.match(page, /roi\.levers\.map/);
  assert.match(page, /lever\.proof\.map/);
  assert.match(page, /visual alerts write 0 records and change 0 ranks/);
  assert.match(page, /decisions@insights/);
  assert.match(page, /0 WRITES/);
  assert.match(intelligence, /buildInsightsBudgetPulse/);
  assert.match(intelligence, /buildInsightsPrivateScopeRadar/);
  assert.match(intelligence, /buildInsightsRoiSwitchboard/);
  assert.match(intelligence, /Budget cap alarm/);
  assert.match(intelligence, /Rate swap candidate/);
  assert.match(intelligence, /Local repeat lane/);
  assert.match(intelligence, /Publish proof lock/);
  assert.match(intelligence, /Private scope radar armed/);
  assert.match(intelligence, /vibetracker stats --account <id>/);
  assert.match(intelligence, /vibetracker stats --profile <id>/);
  assert.match(intelligence, /vibetracker stats --team <id>/);
  assert.match(intelligence, /publicWrites: 0/);
  assert.match(intelligence, /rankMutations: 0/);
  assert.match(intelligence, /planningEstimateUsd/);
  assert.match(intelligence, /hiddenUploads 0/);
  assert.match(intelligence, /promptReads 0/);
  assert.match(intelligence, /totalMutations: 0/);
  assert.match(intelligence, /Set a burn alert/);
  assert.match(intelligence, /Review expensive workflow/);
  assert.match(intelligence, /Shift repeat work local/);
  assert.match(intelligence, /Publish after review/);
  assert.match(intelligence, /Decision cards never write usage records/);
  assert.match(page, /daily aggregates/);
  assert.match(page, /rate estimate/);
  assert.match(page, /review action/);
  assert.match(page, /daily pace/);
  assert.match(page, /30-day forecast/);
  assert.match(page, /planning delta/);
  assert.match(page, /local shadow \/ not spend/);
  assert.match(page, /cheapest source/);
  assert.match(page, /most expensive workflow/);
  assert.match(page, /local shadow value/);
  assert.match(page, /Sample analytics view/);
  assert.match(page, /Vibers Unite/);
  assert.match(page, /C0vibe\.app/);
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/);
  assert.match(styles, /\.insights-route-intro/);
  assert.match(styles, /\.insights-decision-radar/);
  assert.match(styles, /\.insights-decision-radar__terminal::after/);
  assert.match(styles, /\.insights-decision-radar__nodes/);
  assert.match(styles, /\.insights-decision-radar-node--local/);
  assert.match(styles, /\.insights-decision-radar-node--review/);
  assert.match(styles, /\.insights-decision-radar-node__screen pre:nth-child\(2\)/);
  assert.match(styles, /\.insights-decision-radar-node footer i::before/);
  assert.match(styles, /\.insights-private-scope/);
  assert.match(styles, /\.insights-private-scope__terminal::after/);
  assert.match(styles, /\.insights-private-scope__lanes/);
  assert.match(styles, /\.insights-private-scope-lane/);
  assert.match(styles, /\.insights-private-scope-lane--team/);
  assert.match(styles, /\.insights-private-scope-lane\[data-impact="no_write"\]/);
  assert.match(styles, /\.insights-private-scope-lane__screen/);
  assert.match(styles, /\.insights-private-scope-lane__proof/);
  assert.match(styles, /\.insights-private-scope-lane footer i::before/);
  assert.match(styles, /\.insights-budget-pulse/);
  assert.match(styles, /\.insights-budget-pulse__terminal/);
  assert.match(styles, /\.insights-budget-pulse__lanes/);
  assert.match(styles, /\.insights-budget-lane/);
  assert.match(styles, /\.insights-budget-lane__screen/);
  assert.match(styles, /\.insights-budget-lane__transcript/);
  assert.match(styles, /\.insights-budget-lane\[data-impact="not_spend"\]/);
  assert.match(styles, /\.insights-budget-lane\[data-impact="no_write"\]/);
  assert.match(styles, /\.insights-budget-lane footer em::before/);
  assert.match(styles, /\.insights-roi-switchboard/);
  assert.match(styles, /\.insights-roi-terminal/);
  assert.match(styles, /\.insights-roi-terminal__delta/);
  assert.match(styles, /\.insights-roi-levers/);
  assert.match(styles, /\.insights-roi-lever--swap/);
  assert.match(styles, /\.insights-roi-lever\[data-impact="not_spend"\]/);
  assert.match(styles, /\.insights-roi-lever\[data-impact="no_write"\]/);
  assert.match(styles, /\.insights-roi-lever__screen/);
  assert.match(styles, /\.insights-roi-lever__proof/);
  assert.match(styles, /\.insights-roi-lever footer i::before/);
  assert.match(styles, /\.insights-cost-radar/);
  assert.match(styles, /\.insights-cost-radar__terminal/);
  assert.match(styles, /\.insights-cost-radar__path/);
  assert.match(styles, /\.insights-cost-radar__lanes/);
  assert.match(styles, /\.insights-radar-lane--local/);
  assert.match(styles, /\.insights-radar-lane\[data-impact="not_spend"\]/);
  assert.match(styles, /\.insights-radar-lane footer i::before/);
  assert.match(styles, /\.insights-decision-board/);
  assert.match(styles, /\.insights-decision-action--publish/);
  assert.match(styles, /\.insights-decision-action\[data-impact="no_write"\]/);
  assert.match(styles, /\.insights-decision-action__marks/);
  assert.match(styles, /\.insights-decision-action footer i::before/);
  assert.match(styles, /\.insights-lab\.profile-intelligence/);
  assert.match(styles, /prefers-reduced-motion: reduce/);
  assert.match(styles, /\.insights-decision-radar-node__screen pre:first-child/);
  assert.match(styles, /\.insights-private-scope-lane__screen pre:first-child/);
  assert.match(styles, /\.insights-budget-lane__screen pre:first-child/);
  assert.match(styles, /\.insights-roi-lever__screen pre:first-child/);
  assert.match(styles, /\.insights-decision-radar__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.insights-decision-radar__nodes \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.insights-private-scope__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.insights-private-scope__lanes \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.insights-budget-pulse__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.insights-budget-pulse__lanes \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.insights-roi-switchboard__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.insights-roi-levers \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.insights-budget-pulse__lanes \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.insights-roi-levers \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.insights-decision-radar__nodes \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.insights-private-scope__lanes \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.insights-budget-pulse__lanes \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.insights-roi-levers \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /@media \(max-width: 760px\)/);
});
