import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

test("AI life dashboard is exposed as a first-class labelled route", () => {
  const page = readFileSync("packages/web/src/app/life/page.tsx", "utf8");
  const layout = readFileSync("packages/web/src/app/layout.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/globals.css", "utf8");

  assert.match(layout, /href="\/life">AI Life/);
  assert.match(page, /buildAiLifeCockpit/);
  assert.match(page, /life-route-intro/);
  assert.match(page, /AiLifeBroadcastWallPanel/);
  assert.match(page, /AiLifePersonaAtlasPanel/);
  assert.match(page, /AiLifeConstellationPanel/);
  assert.match(page, /AiLifePracticePassportPanel/);
  assert.match(page, /life-broadcast-wall/);
  assert.match(page, /life-broadcast-card/);
  assert.match(page, /life-persona-atlas/);
  assert.match(page, /life-persona-card/);
  assert.match(page, /life-constellation/);
  assert.match(page, /life-orbit/);
  assert.match(page, /life-practice-passport/);
  assert.match(page, /life-practice-surface/);
  assert.match(page, /life-route-cockpit ai-life-cockpit/);
  assert.match(page, /VTK:\/\/AI-LIFE-DASHBOARD\/\/CREATORS-CODERS-LOCAL-GLOBAL\/\/NO-MIXED-RAILS/);
  assert.match(page, /VTK:\/\/AI-LIFE-BROADCAST\/\/VIBERS-UNITE\/\/NOT-JUST-CODERS/);
  assert.match(page, /VTK:\/\/AI-LIFE-PERSONA-ATLAS\/\/NOT-JUST-CODERS\/\/ALL-VIBERS/);
  assert.match(page, /VTK:\/\/AI-LIFE-DASHBOARD\/\/CONSTELLATION\/\/USAGE-TRUST-LOCAL-PUBLISH/);
  assert.match(page, /VTK:\/\/AI-LIFE-CONSTELLATION\/\/ALL-RAILS\/\/NO-MIXED-TOTALS/);
  assert.match(page, /VTK:\/\/AI-LIFE-PASSPORT\/\/CREATOR-BUILDER-LOCAL-RESEARCH\/\/NO-MIXED-RANKS/);
  assert.match(page, /Your whole AI practice, not just coding spend/);
  assert.match(page, /creators, coders, local model users, regional AI explorers/);
  assert.match(page, /Usage, not-usage trust, local-only/);
  assert.match(page, /Vibers Unite/);
  assert.match(page, /C0vibe\.app/);
  assert.match(page, /NO MIXED RAILS/);
  assert.match(page, /Vibers Unite broadcast/);
  assert.match(page, /vibetracker life --broadcast/);
  assert.match(page, /creator studios, builder agents, local labs/);
  assert.match(page, /NO MIXED TOTALS/);
  assert.match(page, /constellation motion writes 0 records, 0 ranks/);
  assert.match(page, /builder trust is NOT USAGE; local AI is LOCAL ONLY/);
  assert.match(page, /privacy review and C0VIBE publish are separate rails/);
  assert.match(page, /lane\.providers\.slice\(0, 5\)/);
  assert.match(page, /lane\.railLabel/);
  assert.match(page, /lane\.providers\.slice\(0, 8\)/);
  assert.match(page, /atlas\.personas\.map/);
  assert.match(page, /card\.tracks/);
  assert.match(page, /card\.notTracked/);
  assert.match(page, /card\.proof/);
  assert.match(page, /persona@life/);
  assert.match(page, /cockpit\.rhythm\.map/);
  assert.match(page, /passport\.surfaces\.map/);
  assert.match(page, /surface\.providers\.map/);
  assert.match(page, /surface\.providers\.slice\(0, 4\)/);
  assert.match(page, /surface\.boundary/);
  assert.match(page, /ALL VIBERS/);
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/);
  assert.match(styles, /\.life-route-intro/);
  assert.match(styles, /\.life-broadcast-wall/);
  assert.match(styles, /\.life-broadcast-wall__terminal::after/);
  assert.match(styles, /\.life-broadcast-cards/);
  assert.match(styles, /\.life-broadcast-card--not_usage/);
  assert.match(styles, /\.life-broadcast-card--local_only/);
  assert.match(styles, /\.life-broadcast-card__providers/);
  assert.match(styles, /\.life-broadcast-card footer i::before/);
  assert.match(styles, /\.life-persona-atlas/);
  assert.match(styles, /\.life-persona-atlas__terminal/);
  assert.match(styles, /\.life-persona-atlas__totals/);
  assert.match(styles, /\.life-persona-cards/);
  assert.match(styles, /\.life-persona-card--not_usage/);
  assert.match(styles, /\.life-persona-card\[data-impact="local_only"\]/);
  assert.match(styles, /\.life-persona-card__providers/);
  assert.match(styles, /\.life-persona-card footer i::before/);
  assert.match(styles, /\.life-constellation/);
  assert.match(styles, /\.life-constellation__terminal/);
  assert.match(styles, /\.life-constellation__map/);
  assert.match(styles, /\.life-constellation__core/);
  assert.match(styles, /\.life-orbit--local_only/);
  assert.match(styles, /\.life-orbit\[data-impact="not_usage"\]/);
  assert.match(styles, /\.life-orbit footer i::before/);
  assert.match(styles, /\.life-practice-passport/);
  assert.match(styles, /\.life-practice-surface--privacy/);
  assert.match(styles, /\.life-practice-surface\[data-impact="local_only"\]/);
  assert.match(styles, /\.life-practice-surface__providers/);
  assert.match(styles, /\.life-practice-surface footer i::before/);
  assert.match(styles, /\.life-route-cockpit\.ai-life-cockpit/);
  assert.match(styles, /prefers-reduced-motion: reduce/);
  assert.match(styles, /\.life-broadcast-wall__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.life-broadcast-cards \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.life-broadcast-cards \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.life-broadcast-cards \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /@media \(max-width: 760px\)/);
});
