import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

test("motion route is a route-local interactive credited sequencer", () => {
  const page = readFileSync("packages/web/src/app/motion/page.tsx", "utf8");
  const sequencer = readFileSync("packages/web/src/app/motion/motion-sequencer.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/motion/motion.css", "utf8");
  const controls = readFileSync("packages/web/src/app/motion/motion-controls.css", "utf8");
  const responsive = readFileSync("packages/web/src/app/motion/motion-responsive.css", "utf8");
  const manifest = readFileSync("packages/web/src/app/motion/module.sweetspot.json", "utf8");
  const layout = readFileSync("packages/web/src/app/layout.tsx", "utf8");

  assert.match(layout, /href="\/motion"/);   // reachable from the header
  assert.match(page, /buildAsciiMotionLab/);
  assert.match(page, /<MotionSequencer lab=/);
  assert.match(page, /\.\/motion\.css/);
  assert.match(page, /\.\/motion-controls\.css/);
  assert.match(page, /\.\/motion-responsive\.css/);
  assert.match(sequencer, /^"use client";/);
  assert.match(sequencer, /type SequenceMode = "cues" \| "rigs"/);
  assert.match(sequencer, /aria-pressed=/);
  assert.match(sequencer, /type="range"/);
  assert.match(sequencer, /setInterval/);
  assert.match(sequencer, /matchMedia\("\(prefers-reduced-motion: reduce\)"\)/);
  assert.match(sequencer, /role="img"/);
  assert.match(sequencer, /<pre aria-hidden="true">/);
  assert.match(sequencer, /navigator\.clipboard\.writeText/);
  assert.match(sequencer, /Clipboard access failed/);
  assert.match(sequencer, /motion never acts as usage evidence/);
  assert.match(sequencer, /providerCalls: 0/);
  assert.match(sequencer, /hiddenUploads: 0/);
  assert.match(sequencer, /usageWrites: 0/);
  assert.match(sequencer, /trustWrites: 0/);
  assert.match(sequencer, /promptReads: 0/);
  assert.match(sequencer, /outputReads: 0/);
  assert.match(sequencer, /publishWrites: 0/);
  assert.match(sequencer, /lab\.references\.length/);
  assert.match(styles, /\.seq-console/);
  assert.match(styles, /\.seq-timeline/);
  assert.match(styles, /\.seq-timeline button i[\s\S]*color: var\(--seq-ink\)/);
  assert.match(styles, /\.seq-screen pre/);
  assert.match(styles, /\.seq-proof/);
  assert.match(controls, /\.seq-modes/);
  assert.match(controls, /\.seq-tempo/);
  assert.match(responsive, /\.seq-sources/);
  assert.match(responsive, /@media \(max-width: 760px\)/);
  assert.match(responsive, /\.seq-cue-copy button \{ min-height: 44px; \}/);
  assert.match(responsive, /prefers-reduced-motion/);
  assert.match(manifest, /000-vibetracker\.web\.motion-sequencer/);
  assert.doesNotMatch(page, /MotionScanDirectorBoard|MotionSignalTheatre|MotionRunwayPanel/);
  assert.doesNotMatch(sequencer, /dangerouslySetInnerHTML/);
});
