import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

test("motion lab route exposes the credited terminal motion runway", () => {
  const page = readFileSync("packages/web/src/app/motion/page.tsx", "utf8");
  const layout = readFileSync("packages/web/src/app/layout.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/globals.css", "utf8");

  assert.match(layout, /href="\/motion"><span>06<\/span>Motion lab/);
  assert.match(page, /buildAsciiMotionLab/);
  assert.match(page, /MotionScanDirectorBoard/);
  assert.match(page, /motion-director-board/);
  assert.match(page, /MOTION-DIRECTOR\/\/LIVE-SCAN\/\/SIDE-EFFECT-ZERO/);
  assert.match(page, /director@motion-lab/);
  assert.match(page, /VISUAL ONLY/);
  assert.match(page, /Codex cube -> Higgsfield prism -> local sonar -> map snap/);
  assert.match(page, /prompt reads 0 output reads 0 hidden uploads 0/);
  assert.match(page, /beat\.sideEffects\.publishWrites/);
  assert.match(page, /motion-director-timeline/);
  assert.match(page, /MotionSignalTheatre/);
  assert.match(page, /motion-signal-theatre/);
  assert.match(page, /SIGNAL-THEATRE\/\/SURPRISE-SEQUENCE\/\/ZERO-SIDEFX/);
  assert.match(page, /signal@motion-lab/);
  assert.match(page, /ZERO SIDEFX/);
  assert.match(page, /beat\.frames\.map/);
  assert.match(page, /beat\.checks\.map/);
  assert.match(page, /sideEffects\.promptReads/);
  assert.match(page, /total sidefx/);
  assert.match(page, /MotionRunwayPanel/);
  assert.match(page, /Native terminal graphics/);
  assert.match(page, /vibetracker motion --references native/);
  assert.match(page, /TerminalTextEffects \/ Notcurses \/ Chafa/);
  assert.match(page, /no Python, native, GPL, or LGPL runtime is bundled/);
  assert.match(page, /native terminal graphics stay credited as reference-only/);
  assert.match(page, /motion-runway/);
  assert.match(page, /MOTION-RUNWAY\/\/OSS-ATTRIBUTED\/\/NO-RUNTIME-GPL/);
  assert.match(page, /runway@motion-lab/);
  assert.match(page, /NO FAKE PROOF/);
  assert.match(page, /cli-spinners ascii-globe MapSCII drawille pipes HF/);
  assert.match(page, /TerminalTextEffects Notcurses Chafa are native refs/);
  assert.match(page, /GPL refs are not bundled/);
  assert.match(page, /animation labels never change usage, trust, or rank/);
  assert.match(page, /lab\.rigs\.map/);
  assert.match(page, /rig\.frames\.map/);
  assert.match(page, /rig\.glyphs\.map/);
  assert.match(page, /linuxBench\.length/);
  assert.match(page, /referenceOnly/);
  assert.match(page, /Vibers Unite/);
  assert.match(page, /C0vibe\.app/);
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/);

  assert.match(styles, /\.motion-runway/);
  assert.match(styles, /\.motion-director-board/);
  assert.match(styles, /\.motion-director-board__terminal/);
  assert.match(styles, /\.motion-director-timeline/);
  assert.match(styles, /\.motion-director-cue/);
  assert.match(styles, /\.motion-director-cue__screen pre:first-child/);
  assert.match(styles, /\.motion-director-cue__meter i/);
  assert.match(styles, /\.motion-attribution-lane--native/);
  assert.match(styles, /\.motion-signal-theatre/);
  assert.match(styles, /\.motion-signal-theatre__terminal/);
  assert.match(styles, /\.motion-signal-board/);
  assert.match(styles, /\.motion-signal-beat/);
  assert.match(styles, /\.motion-signal-beat__stage pre:first-child/);
  assert.match(styles, /\.motion-signal-ledger/);
  assert.match(styles, /\.motion-runway__terminal/);
  assert.match(styles, /\.motion-runway__lanes/);
  assert.match(styles, /\.motion-runway-lane/);
  assert.match(styles, /\.motion-runway-lane__screen pre:first-child/);
  assert.match(styles, /\.motion-runway-lane__glyphs/);
  assert.match(styles, /\.motion-runway-lane__meter i/);
  assert.match(styles, /SPIN \/ GLOBE \/ MAP \/ BRAILLE \/ PIPES \/ TURNTABLE/);
  assert.match(styles, /CODEX \/ HIGGSFIELD \/ LOCAL \/ REGIONAL \/ PROOF \/ C0VIBE/);
  assert.match(styles, /prefers-reduced-motion: reduce/);
  assert.match(styles, /\.motion-director-cue__screen pre:first-child \{ opacity: 1; \}/);
  assert.match(styles, /\.motion-signal-beat__stage pre:first-child \{ opacity: 1; \}/);
  assert.match(styles, /\.motion-runway-lane__screen pre:first-child \{ opacity: 1; \}/);
  assert.match(styles, /@media \(max-width: 1180px\)/);
  assert.match(styles, /\.motion-director-board__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.motion-signal-theatre__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.motion-runway__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /@media \(max-width: 460px\)/);
  assert.match(styles, /\.motion-director-timeline \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.motion-signal-board \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.motion-runway__lanes \{ grid-template-columns: 1fr; \}/);
});
