import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

test("public profile route exposes a shareable signal tower with separated rails", () => {
  const page = readFileSync("packages/web/src/app/u/[handle]/page.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/globals.css", "utf8");

  assert.match(page, /ProfileSignalTowerPanel/);
  assert.match(page, /ProfilePublicRelayCockpitPanel/);
  assert.match(page, /ProfileViberCardPanel/);
  assert.match(page, /ProfileWalletPassPanel/);
  assert.match(page, /const heroTransmissionRails/);
  assert.match(page, /profile-hero-transmission/);
  assert.match(page, /Public profile first-screen transmission rails/);
  assert.match(page, /Score seal/);
  assert.match(page, /Usage proof/);
  assert.match(page, /Trust side rail/);
  assert.match(page, /Privacy seal/);
  assert.match(page, /C0VIBE relay/);
  assert.match(page, /Trust context cannot inflate the score/);
  assert.match(page, /Never changes spend, credits, operations, or rank/);
  assert.match(page, /hidden uploads 0; prompt reads 0; output reads 0/);
  assert.match(page, /profile-signal-tower/);
  assert.match(page, /profile-public-relay-cockpit/);
  assert.match(page, /profile-public-relay-cockpit__stages/);
  assert.match(page, /VTK:\/\/PUBLIC-RELAY-COCKPIT\/\/SHARE-FIRST\/\/NO-MIXED-SIGNALS/);
  assert.match(page, /VTK:\/\/PROFILE-VIBER-CARD\/\/MOBILE-READABLE\/\/C0VIBE\.APP/);
  assert.match(page, /VTK:\/\/PROFILE-WALLET-PASS\/\/POCKET-PROOF\/\/C0VIBE\.APP/);
  assert.match(page, /VTK:\/\/PUBLIC-SIGNAL-TOWER\/\/SCORE-USAGE-TRUST-PUBLISH\/\/C0VIBE\.APP/);
  assert.match(page, /VTK:\/\/PUBLIC-SIGNAL-TOWER/);
  assert.match(page, /C0VIBE public wallet pass/);
  assert.match(page, /wallet@profile/);
  assert.match(page, /Deterministic wallet pass verification matrix/);
  assert.match(page, /pass\.seals\.map/);
  assert.match(page, /pass\.chips\.map/);
  assert.match(page, /pocket-readable Viber card/);
  assert.match(page, /A phone-first share card/);
  assert.match(page, /same reviewed datastream behind score, heatgrid, profile, and public relay/);
  assert.match(page, /Score, usage, rhythm, sources, trust, and C0VIBE publish/);
  assert.match(page, /usage -> heatgrid -> score -> profile -> C0VIBE relay/);
  assert.match(page, /NO RAW PROMPTS/);
  assert.match(page, /0 hidden uploads/);
  assert.match(page, /0 raw reads/);
  assert.match(page, /rawPromptReads=0 rawOutputReads=0 hiddenUploads=0/);
  assert.match(page, /usage datastream/);
  assert.match(page, /trust != usage/);
  assert.match(page, /aggregate only/);
  assert.match(page, /trust is NOT USAGE/);
  assert.match(page, /No prompt text, output text, secrets, or raw files are published/);
  assert.match(page, /Trust never changes spend, credits, operations, rank, or verified provider totals/);
  assert.match(page, /Social, GitHub, MCP, and creator cadence cannot move spend/);
  assert.match(page, /No prompts, outputs, secrets, or raw files in the public card/);
  assert.match(page, /Explicit public destination after reviewed aggregate upload/);
  assert.match(page, /official GitHub contribution scale/);
  assert.match(page, /profileSignalTowerLabel/);
  assert.match(page, /profileSignalTowerFrames/);
  assert.match(page, /bridge\.stages\.map/);
  assert.match(page, /receipt\.seal/);
  assert.match(page, /datastreamReceipt/);
  assert.match(page, /Vibers Unite/);
  assert.match(page, /c0vibe\.app/);
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/);

  assert.match(styles, /\.profile-public-relay-cockpit/);
  assert.match(styles, /\.profile-hero-transmission/);
  assert.match(styles, /\.profile-hero-transmission-rail--trust/);
  assert.match(styles, /\.profile-hero-transmission-rail--privacy/);
  assert.match(styles, /\.profile-hero-transmission-rail__cells span/);
  assert.match(styles, /SHARE SEAL \/ USAGE \/ TRUST \/ PRIVACY \/ RELAY/);
  assert.match(styles, /\.profile-public-relay-cockpit__terminal/);
  assert.match(styles, /\.profile-public-relay-cockpit__stages/);
  assert.match(styles, /\.profile-public-relay-stage/);
  assert.match(styles, /\.profile-public-relay-stage__screen pre:first-child/);
  assert.match(styles, /\.profile-public-relay-stage\[data-impact="NOT USAGE"\]/);
  assert.match(styles, /\.profile-viber-card/);
  assert.match(styles, /\.profile-viber-card__terminal/);
  assert.match(styles, /\.profile-viber-card__seals/);
  assert.match(styles, /\.profile-viber-card__lanes/);
  assert.match(styles, /\.profile-viber-card-lane/);
  assert.match(styles, /\.profile-viber-card-lane\[data-impact="NOT USAGE"\]/);
  assert.match(styles, /\.profile-viber-card-lane\[data-impact="PRIVACY"\]/);
  assert.match(styles, /\.profile-viber-card-lane\[data-impact="PUBLISH"\]/);
  assert.match(styles, /\.profile-wallet-pass/);
  assert.match(styles, /\.profile-wallet-pass__terminal/);
  assert.match(styles, /\.profile-wallet-pass__matrix/);
  assert.match(styles, /\.profile-wallet-pass__chips/);
  assert.match(styles, /\.profile-wallet-pass__chips article\[data-impact="NOT USAGE"\]/);
  assert.match(styles, /WALLET PASS/);
  assert.match(styles, /\.profile-signal-tower/);
  assert.match(styles, /\.profile-signal-tower__terminal/);
  assert.match(styles, /\.profile-signal-tower__rails/);
  assert.match(styles, /\.profile-signal-tower-rail/);
  assert.match(styles, /\.profile-signal-tower-rail__scope pre:first-child/);
  assert.match(styles, /\.profile-signal-tower-rail\[data-impact="NOT USAGE"\]/);
  assert.match(styles, /@media \(max-width: 1040px\)/);
  assert.match(styles, /\.profile-hero-transmission \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.profile-public-relay-cockpit__stages \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 1040px\)[\s\S]*\.profile-viber-card__lanes \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 1040px\)[\s\S]*\.profile-wallet-pass__chips \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.profile-viber-card__lanes \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.profile-wallet-pass__chips \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 460px\)/);
  assert.match(styles, /\.profile-hero-transmission \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /prefers-reduced-motion: reduce[\s\S]*\.profile-hero-transmission-rail__cells span \{ transform: none; \}/);
  assert.match(styles, /prefers-reduced-motion: reduce[\s\S]*\.profile-viber-card__terminal::after, \.profile-viber-card-lane::after, \.profile-viber-card-lane footer em::before \{ transform: none; \}/);
  assert.match(styles, /\.profile-public-relay-cockpit__stages \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /@media \(max-width: 460px\)[\s\S]*\.profile-viber-card__lanes \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.profile-public-relay-stage__screen pre:first-child \{ opacity: 1; \}/);
  assert.match(styles, /\.profile-wallet-pass__terminal::after, \.profile-wallet-pass__card::after \{ transform: none; \}/);
  assert.match(styles, /@media \(max-width: 460px\)[\s\S]*\.profile-wallet-pass__chips \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.profile-signal-tower__rails \{ grid-template-columns: 1fr; \}/);
});
