import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

test("proof center is exposed as a first-class local-first evidence route", () => {
  const page = readFileSync("packages/web/src/app/proof/page.tsx", "utf8");
  const layout = readFileSync("packages/web/src/app/layout.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/globals.css", "utf8");
  const evidence = readFileSync("packages/web/src/lib/evidence-cockpit.ts", "utf8");

  assert.match(layout, /href="\/proof"><span>03<\/span>Proof center/);
  assert.match(page, /buildEvidenceCockpit/);
  assert.match(page, /proof-route-intro/);
  assert.match(page, /proof-route-cockpit evidence-cockpit/);
  assert.match(page, /VTK:\/\/PROOF-CENTER\/\/LOCAL-FIRST\/\/NO-FAKE-PROOF\/\/NO-HIDDEN-UPLOADS/);
  assert.match(page, /Fast collection is useless without visible proof/);
  assert.match(page, /provider collection, ingest validation/);
  assert.match(page, /local redaction preview/);
  assert.match(page, /not-usage trust rails/);
  assert.match(page, /explicit C0VIBE publish relay/);
  assert.match(page, /NO FAKE PROOF/);
  assert.match(page, /dry-run first/);
  assert.match(page, /railLabelFor/);
  assert.match(page, /NOT USAGE/);
  assert.match(page, /LOCAL ONLY/);
  assert.match(page, /PUBLISH/);
  assert.match(page, /Vibers Unite/);
  assert.match(page, /c0vibe\.app/);
  assert.match(page, /ProofDatastreamSpinePanel/);
  assert.match(page, /proof-datastream-spine/);
  assert.match(page, /VTK:\/\/DATASTREAM-SPINE\/\/SCORE-PROFILE-PUBLISH\/\/TRUST-SIDECAR/);
  assert.match(page, /One reviewed receipt, four honest surfaces/);
  assert.match(page, /same accepted aggregate receipt/);
  assert.match(page, /score feeds from usage/);
  assert.match(page, /profile feeds from receipt/);
  assert.match(page, /trust is not usage/);
  assert.match(page, /id: "trust"/);
  assert.match(page, /evidence\.bridge\.totals\.trustUsageWrites/);
  assert.match(page, /evidence\.bridge\.totals\.zeroHiddenUploads/);
  assert.match(page, /vibetracker upload --target c0vibe/);
  assert.match(page, /ProofBlackBoxPanel/);
  assert.match(page, /proof-black-box/);
  assert.match(page, /VTK:\/\/BLACK-BOX\/\/CUSTODY\/\/NO-RAW-PROMPTS\/\/0-HIDDEN-UPLOADS/);
  assert.match(page, /USAGE \+ TRUST \+ PRIVACY \+ PUBLISH/);
  assert.match(page, /0 hidden uploads/);
  assert.match(page, /NO RAW PROMPTS/);
  assert.match(page, /NOT USAGE labels/);
  assert.match(page, /link\.command/);
  assert.match(page, /custodyToneFor/);
  assert.match(page, /ProofVerificationBridgePanel/);
  assert.match(page, /proof-verification-bridge/);
  assert.match(page, /VTK:\/\/PROOF-BRIDGE\/\/OPERATOR-QUESTIONS\/\/ZERO-HIDDEN-UPLOADS/);
  assert.match(page, /bridge@proof/);
  assert.match(page, /bridge\.totals\.trustUsageWrites/);
  assert.match(page, /bridge\.gates\.map/);
  assert.match(page, /gate\.question/);
  assert.match(page, /gate\.writes/);
  assert.match(page, /gate\.invariant/);
  assert.match(page, /bridgeToneFor/);
  assert.match(page, /ProofReplayRecorderPanel/);
  assert.match(page, /proof-replay-recorder/);
  assert.match(page, /VTK:\/\/PROOF-REPLAY\/\/TAMPER-EVIDENT\/\/LOCAL-FIRST\/\/NOT-USAGE-SIDECAR/);
  assert.match(page, /replay\.terminalLines/);
  assert.match(page, /event\.hash/);
  assert.match(page, /event\.invariant/);
  assert.match(page, /replayToneFor/);
  assert.match(evidence, /vibetracker upload --target c0vibe/);
  assert.match(evidence, /C0VIBE datastream/);
  assert.match(evidence, /vibetracker trust scan/);
  assert.match(evidence, /Tamper-evident replay/);
  assert.match(evidence, /sha256:c0vibe-profile-feed/);
  assert.match(evidence, /trust sidecars are NOT USAGE/);
  assert.match(evidence, /Verification bridge/);
  assert.match(evidence, /What counts\?/);
  assert.match(evidence, /What leaves\?/);
  assert.match(evidence, /0 usage writes/);
  assert.match(evidence, /0 hidden uploads/);
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/);
  assert.match(styles, /\.proof-route-intro/);
  assert.match(styles, /\.proof-datastream-spine/);
  assert.match(styles, /\.proof-datastream-spine__terminal::after/);
  assert.match(styles, /\.proof-datastream-spine__nodes/);
  assert.match(styles, /\.proof-spine-node--trust/);
  assert.match(styles, /\.proof-spine-node__screen pre:nth-child\(2\)/);
  assert.match(styles, /\.proof-spine-node footer i::before/);
  assert.match(styles, /\.proof-route-cockpit\.evidence-cockpit/);
  assert.match(styles, /\.proof-black-box/);
  assert.match(styles, /\.proof-custody-link--trust/);
  assert.match(styles, /\.proof-verification-bridge/);
  assert.match(styles, /\.proof-verification-bridge__terminal/);
  assert.match(styles, /\.proof-verification-bridge__totals/);
  assert.match(styles, /\.proof-verification-gate--not_usage/);
  assert.match(styles, /\.proof-verification-gate__screen/);
  assert.match(styles, /\.proof-verification-gate__checks/);
  assert.match(styles, /\.proof-verification-gate footer i::before/);
  assert.match(styles, /\.proof-replay-recorder/);
  assert.match(styles, /\.proof-replay-event--sidecar/);
  assert.match(styles, /\.proof-replay-event__hash/);
  assert.match(styles, /\.proof-replay-event__meter i/);
  assert.match(styles, /@keyframes proof-custody-frame/);
  assert.match(styles, /\.proof-custody-link__scope pre:first-child/);
  assert.match(styles, /attr\(data-rail\)/);
  assert.match(styles, /attr\(data-status\)/);
  assert.match(styles, /\.proof-datastream-spine__body \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.proof-datastream-spine__nodes \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /@media \(max-width: 760px\)/);
});
