import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

test("scan room is exposed as a first-class visual-only collection route", () => {
  const page = readFileSync("packages/web/src/app/scan/page.tsx", "utf8");
  const layout = readFileSync("packages/web/src/app/layout.tsx", "utf8");
  const styles = readFileSync("packages/web/src/app/globals.css", "utf8");

  assert.match(layout, /href="\/scan"><span>02<\/span>Scan room/);
  assert.match(page, /buildCollectionSurpriseRun/);
  assert.match(page, /buildCollectionBlackBox/);
  assert.match(page, /buildCollectionCommandRunway/);
  assert.match(page, /buildCollectionHeroScanBridge/);
  assert.match(page, /buildCollectionTransmissionRibbon/);
  assert.match(page, /buildCollectionSurpriseDirector/);
  assert.match(page, /buildCollectionSurpriseCascade/);
  assert.match(page, /buildCollectionFlightRecorder/);
  assert.match(page, /buildCollectionEventTape/);
  assert.match(page, /buildCollectionSignalStack/);
  assert.match(page, /buildCollectionSurpriseSequencer/);
  assert.match(page, /buildCollectionReplayDeck/);
  assert.match(page, /buildCollectionEncoreRecap/);
  assert.match(page, /scan-route-intro/);
  assert.match(page, /ScanRoomPulseMasthead/);
  assert.match(page, /VTK:\/\/SCAN-PULSE\/\/VISUAL-ONLY\/\/ZERO-WRITES/);
  assert.match(page, /ScanSignalEqualizer/);
  assert.match(page, /SCAN_EQUALIZER_SIDE_EFFECTS/);
  assert.match(page, /VTK:\/\/SCAN-EQUALIZER\/\/SIGNATURE-REVEALS\/\/ZERO-SIDE-EFFECTS/);
  assert.match(page, /equalizerBars/);
  assert.match(page, /equalizer@scan-room/);
  assert.match(page, /providerCalls=0/);
  assert.match(page, /ledgerWrites=0/);
  assert.match(page, /hiddenUploads=0/);
  assert.match(page, /promptReads=0/);
  assert.match(page, /HF prism -> Codex cube -> local sonar -> C0VIBE flash/);
  assert.match(page, /scan-signal-equalizer/);
  assert.match(page, /scan-equalizer-channel__bars/);
  assert.match(page, /ScanSignalEqualizer bridge=\{bridge\}/);
  assert.match(page, /bridge\.totals\.surprises/);
  assert.match(page, /bridge\.totals\.usageWrites/);
  assert.match(page, /bridge\.stages\.slice\(0, 4\)\.map/);
  assert.match(page, /scan-route-pulse-rail/);
  assert.match(page, /ScanRoomPulseMasthead bridge=\{bridge\}/);
  assert.match(page, /scan-route-hero/);
  assert.match(page, /collection-hero-scan-bridge/);
  assert.match(page, /HERO-SCAN-BRIDGE/);
  assert.match(page, /bridge\.stages\.map/);
  assert.match(page, /stage\.frames\.map/);
  assert.match(page, /stage\.railLabel/);
  assert.match(page, /bridge\.totals\.usageWrites/);
  assert.match(page, /ScanCommandRunwayPanel/);
  assert.match(page, /scan-command-runway/);
  assert.match(page, /SCAN-ROOM\/\/COMMAND-RUNWAY\/\/LIVE-GUI\/\/NO-FAKE-USAGE/);
  assert.match(page, /runway@scan-room/);
  assert.match(page, /runway\.steps\.map/);
  assert.match(page, /step\.transcript\.map/);
  assert.match(page, /step\.usageWrites/);
  assert.match(page, /ScanLogoEncoreReelPanel/);
  assert.match(page, /scan-logo-encore-reel/);
  assert.match(page, /SURPRISE-RIBBON\/\/LOGO-ENCORE\/\/SCAN-COLLECT\/\/NO-FAKE-SPEND/);
  assert.match(page, /logo-reel@scan-room/);
  assert.match(page, /HF CX 127 C0/);
  assert.match(page, /ribbon\.steps\.map/);
  assert.match(page, /railLabelFor\(step\.impact\)/);
  assert.match(page, /step\.frames\.map/);
  assert.match(page, /logo encore marks/);
  assert.match(page, /cli-spinners\|ascii-globe\|drawille/);
  assert.match(page, /ScannerSurpriseDirectorPanel/);
  assert.match(page, /CollectionSurpriseCascadePanel/);
  assert.match(page, /scanner-surprise-director/);
  assert.match(page, /scanner-director-cues/);
  assert.match(page, /collection-surprise-cascade/);
  assert.match(page, /collection-cascade-beats/);
  assert.match(page, /director\.cues\.map/);
  assert.match(page, /cascade\.beats\.map/);
  assert.match(page, /SCAN-ROOM\/\/SURPRISE-DIRECTOR\/\/SHOWRUN\/\/NO-FAKE-PROOF/);
  assert.match(page, /SCAN-ROOM\/\/SURPRISE-CASCADE\/\/SCAN-COLLECT\/\/NO-FAKE-PROOF/);
  assert.match(page, /ScannerBlackBoxPanel/);
  assert.match(page, /scanner-black-box/);
  assert.match(page, /scanner-black-cell/);
  assert.match(page, /blackBox\.cells\.map/);
  assert.match(page, /SCAN-ROOM\/\/SCANNER-BLACK-BOX\/\/LOCAL-REPLAY\/\/NO-PROMPTS/);
  assert.match(page, /REPLAY HASH/);
  assert.match(page, /cell\.checksum/);
  assert.match(page, /collection-flight-recorder/);
  assert.match(page, /collection-signal-stack/);
  assert.match(page, /collection-surprise-sequencer/);
  assert.match(page, /scan-replay-recorder/);
  assert.match(page, /collection-encore-recap/);
  assert.match(page, /VTK:\/\/SCAN-ROOM/);
  assert.match(page, /NO USAGE WRITES/);
  assert.match(page, /visualOnly=true/);
  assert.match(page, /NOT USAGE/);
  assert.match(page, /Vibers Unite/);
  assert.match(page, /C0vibe\.app/);
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/);
  assert.match(styles, /\.scan-route-intro/);
  assert.match(styles, /\.scan-route-pulse/);
  assert.match(styles, /\.scan-route-pulse__rails/);
  assert.match(styles, /\.scan-route-pulse-rail\[data-rail="NOT USAGE"\]/);
  assert.match(styles, /\.scan-route-pulse-rail > i::before/);
  assert.match(styles, /\.scan-signal-equalizer/);
  assert.match(styles, /\.scan-signal-equalizer__terminal/);
  assert.match(styles, /\.scan-signal-equalizer__channels/);
  assert.match(styles, /\.scan-equalizer-channel\[data-rail="NOT USAGE"\]/);
  assert.match(styles, /\.scan-equalizer-channel__bars i/);
  assert.match(styles, /\.scan-signal-equalizer__scope/);
  assert.match(styles, /\.collection-hero-scan-bridge/);
  assert.match(styles, /\.collection-hero-scan-stage/);
  assert.match(styles, /\.scan-command-runway/);
  assert.match(styles, /\.scan-command-runway__terminal/);
  assert.match(styles, /\.scan-command-runway__steps/);
  assert.match(styles, /\.scan-command-runway-step__screen/);
  assert.match(styles, /\.scan-command-runway-step__transcript/);
  assert.match(styles, /\.scan-logo-encore-reel/);
  assert.match(styles, /HF TURN \/ CODEX CUBE \/ LOCAL SONAR \/ VIBERS UNITE/);
  assert.match(styles, /\.scan-logo-encore-reel \.surprise-transmission-step/);
  assert.match(styles, /\.scan-logo-encore-reel \.surprise-transmission-step__screen/);
  assert.match(styles, /\.scanner-surprise-director/);
  assert.match(styles, /\.scanner-director-cue/);
  assert.match(styles, /\.collection-surprise-cascade/);
  assert.match(styles, /\.collection-cascade-beat/);
  assert.match(styles, /\.scanner-black-box/);
  assert.match(styles, /\.scanner-black-cell/);
  assert.match(styles, /\.scan-route-hero\.collection-flight-recorder/);
  assert.match(styles, /@media \(max-width: 760px\)/);
  assert.match(styles, /\.scan-route-pulse__rails \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.scan-signal-equalizer__channels \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /\.scan-logo-encore-reel \.surprise-transmission-step \{ min-height: 300px; \}/);
  assert.match(styles, /\.scan-command-runway__steps \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/);
  assert.match(styles, /@media \(max-width: 460px\)/);
  assert.match(styles, /\.scan-route-pulse__rails \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.scan-signal-equalizer__channels \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.scan-logo-encore-reel \.surprise-transmission-step \{ min-height: 276px; \}/);
  assert.match(styles, /\.scan-command-runway__steps \{ grid-template-columns: 1fr; \}/);
});
