export interface AdapterScaffoldFile {
  path: string;
  content: string;
}

function pascal(id: string): string {
  return id.split(/[-_]/).filter(Boolean).map((s) => s[0]?.toUpperCase() + s.slice(1)).join("");
}

export function adapterScaffold(id: string): AdapterScaffoldFile[] {
  const name = id.replace(/[^a-z0-9_-]/gi, "").toLowerCase();
  if (!name) throw new Error("adapter id must contain letters or numbers");
  const type = pascal(name);
  return [
    {
      path: `packages/adapters/src/${name}/client.ts`,
      content: `export interface ${type}UsageItem {
  id: string;
  created_at: string;
  amount: number;
}

export interface ${type}Client {
  usage(): Promise<${type}UsageItem[]>;
}

export function createFixtureClient(items: ${type}UsageItem[]): ${type}Client {
  return { usage: async () => items };
}
`,
    },
    {
      path: `packages/adapters/src/${name}/normalize.ts`,
      content: `import type { NormalizedRecord } from "../../../core/src/schema/record.ts";
import type { ${type}UsageItem } from "./client.ts";

export function normalizeUsage(items: ${type}UsageItem[]): NormalizedRecord[] {
  return items.filter((item) => item.amount > 0).map((item) => ({
    ts: new Date(item.created_at).toISOString(),
    provider: "${name}",
    category: "other",
    operation: "usage",
    quantity: 1,
    unit: "request",
    rawAmount: item.amount,
    rawUnit: "request",
    source: "ledger",
    confidence: "medium",
    verified: false,
  }));
}
`,
    },
    {
      path: `packages/adapters/src/${name}/index.ts`,
      content: `import type { Adapter } from "../../../core/src/adapter.ts";
import type { ${type}Client } from "./client.ts";
import { normalizeUsage } from "./normalize.ts";

export function create${type}Adapter(client: ${type}Client): Adapter {
  return {
    id: "${name}",
    label: "${type}",
    categories: ["other"],
    auth: "apiKey",
    capabilities: { ledger: true, balance: false, feed: false },
    getUsage: async () => normalizeUsage(await client.usage()),
  };
}

export { createFixtureClient } from "./client.ts";
export { normalizeUsage } from "./normalize.ts";
`,
    },
    {
      path: `packages/adapters/src/${name}/__fixtures__/usage.sample.json`,
      content: `[
  { "id": "sample-1", "created_at": "2026-07-01T00:00:00Z", "amount": 1 }
]
`,
    },
    {
      path: `packages/adapters/src/${name}/__tests__/normalize.test.ts`,
      content: `import { test } from "node:test";
import assert from "node:assert/strict";
import sample from "../__fixtures__/usage.sample.json" with { type: "json" };
import { normalizeUsage } from "../normalize.ts";

test("${name} normalizer emits positive usage records", () => {
  const records = normalizeUsage(sample);
  assert.equal(records.length, 1);
  assert.equal(records[0].provider, "${name}");
  assert.equal(records[0].verified, false);
});
`,
    },
    {
      path: `packages/adapters/src/${name}/README.md`,
      content: `# ${type} Adapter

Generated by \`vibetracker adapter scaffold ${name}\`.

Before marking this adapter \`built\` in the registry:

- Verify the provider endpoint and auth scope.
- Add realistic, redacted fixtures.
- Prove zero/failed/free rows are skipped.
- Add balance/feed tests if the provider supports them.
- Run \`pnpm test:unit\` and \`pnpm telemetry:audit:strict\`.
`,
    },
  ];
}
